name: Ruby on Rails CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rails_test

    steps:
    - uses: actions/checkout@v4
    - name: Install OpenCV
      run: sudo apt-get update && sudo apt-get install -y libopencv-dev libopencv-contrib-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.0'  # Specify the Ruby version here
        bundler-cache: true
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/rails_test

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rspec
