name: Ruby on Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: mydb
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopencv-dev \
            libopencv-calib3d-dev \
            libopencv-contrib-dev \
            libopencv-core-dev \
            libopencv-features2d-dev \
            libopencv-flann-dev \
            libopencv-highgui-dev \
            libopencv-imgcodecs-dev \
            libopencv-imgproc-dev \
            libopencv-ml-dev \
            libopencv-objdetect-dev \
            libopencv-photo-dev \
            libopencv-shape-dev \
            libopencv-stitching-dev \
            libopencv-superres-dev \
            libopencv-video-dev \
            libopencv-videoio-dev \
            libopencv-videostab-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rails test
