name: Ruby on Rails CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.3.2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libopencv-dev
        gem install bundler
        bundle install

    - name: Run tests
      run: bundle exec rake
