name: Ruby on Rails CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2.0'  # Update this to the required version
      - name: Install dependencies
        run: bundle install
      - name: Build and test
        run: bundle exec rspec
